//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SISEF : DbContext
    {
        public SISEF()
            : base("name=SISEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acuerdo> Acuerdo { get; set; }
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<DependenciaFideicomisoEjercicio> DependenciaFideicomisoEjercicio { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<Fideicomiso> Fideicomiso { get; set; }
        public virtual DbSet<Normatividad> Normatividad { get; set; }
        public virtual DbSet<Seguimiento> Seguimiento { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<StatusSesion> StatusSesion { get; set; }
        public virtual DbSet<TipoCalendarizacion> TipoCalendarizacion { get; set; }
        public virtual DbSet<TipoSesion> TipoSesion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioFideicomiso> UsuarioFideicomiso { get; set; }
        public virtual DbSet<StatusAcuerdo> StatusAcuerdo { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Actas> Actas { get; set; }
        public virtual DbSet<FichaTecnica> FichaTecnica { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
    
        public virtual ObjectResult<pa_Acuerdos_Result> pa_Acuerdos(Nullable<int> fideicomiso, Nullable<int> ejercicio, Nullable<int> status, Nullable<int> sesion)
        {
            var fideicomisoParameter = fideicomiso.HasValue ?
                new ObjectParameter("fideicomiso", fideicomiso) :
                new ObjectParameter("fideicomiso", typeof(int));
    
            var ejercicioParameter = ejercicio.HasValue ?
                new ObjectParameter("ejercicio", ejercicio) :
                new ObjectParameter("ejercicio", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var sesionParameter = sesion.HasValue ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Acuerdos_Result>("pa_Acuerdos", fideicomisoParameter, ejercicioParameter, statusParameter, sesionParameter);
        }
    }
}
