//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISEF : DbContext
    {
        public SISEF()
            : base("name=SISEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acuerdo> Acuerdo { get; set; }
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<DependenciaFideicomisoEjercicio> DependenciaFideicomisoEjercicio { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<Fideicomiso> Fideicomiso { get; set; }
        public virtual DbSet<Normatividad> Normatividad { get; set; }
        public virtual DbSet<Seguimiento> Seguimiento { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<StatusSesion> StatusSesion { get; set; }
        public virtual DbSet<TipoCalendarizacion> TipoCalendarizacion { get; set; }
        public virtual DbSet<TipoSesion> TipoSesion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioDependencia> UsuarioDependencia { get; set; }
    }
}
