//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptSintesisInformativaHistorico
    {
        public int ID { get; set; }
        public Nullable<int> FideicomisoID { get; set; }
        public string NombreFideicomiso { get; set; }
        public string NombreCampo { get; set; }
        public string ValorCampo { get; set; }
        public Nullable<int> FichaTecnicaID { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
