//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public Sesion()
        {
            this.Acuerdo = new HashSet<Acuerdo>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
    
        public int ID { get; set; }
        public int CalendarioID { get; set; }
        public int Mes { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaCelebrada { get; set; }
        public Nullable<System.DateTime> FechaReprogramada { get; set; }
        public int TipoSesionID { get; set; }
        public int StatusSesionID { get; set; }
        public int TipoCalendarizacionID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioCaptura { get; set; }
        public string UsuarioModifica { get; set; }
    
        public virtual ICollection<Acuerdo> Acuerdo { get; set; }
        public virtual Calendario Calendario { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        public virtual StatusSesion StatusSesion { get; set; }
        public virtual TipoCalendarizacion TipoCalendarizacion { get; set; }
        public virtual TipoSesion TipoSesion { get; set; }
    }
}
