//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.DetalleUsuariosDependencia = new HashSet<UsuarioDependencia>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public int TipoUsuarioID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
    
        public virtual ICollection<UsuarioDependencia> DetalleUsuariosDependencia { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
